<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{5ba6c13a-6ac1-4f7a-9948-296da78edcb1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	udp1:  SampleUdpEchoServer;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
udp1();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>